[General]
__userfile__=true

[desktopswitch]
alignment=Left

[fancymenu]
favorites\1\desktopFile=/usr/share/applications/firefox-esr.desktop
favorites\2\desktopFile=/usr/share/applications/xfce4-terminal.desktop
favorites\3\desktopFile=/usr/share/applications/featherpad.desktop
favorites\4\desktopFile=/usr/share/applications/qps.desktop
favorites\5\desktopFile=/usr/share/applications/lxqt-config-monitor.desktop
favorites\size=5

[mount]
alignment=Right

[taskbar]
alignment=Left

[tray]
alignment=Right

[volume]
alignment=Right

[worldclock]
alignment=Right
