[General]
__userfile__=true

[fancymenu]
favorites\1\desktopFile=/home/agustin/.local/share/applications/firefox-tab.desktop
favorites\2\desktopFile=/home/agustin/.local/share/applications/xfce4-terminal-tab.desktop
favorites\3\desktopFile=/usr/share/applications/featherpad.desktop
favorites\4\desktopFile=/usr/share/applications/qps.desktop
favorites\5\desktopFile=/usr/share/applications/lxqt-config-monitor.desktop
favorites\size=5
icon=/home/agustin/.local/share/icons/Windows-7/extras/start-here/debian.png
ownIcon=true

[mount]
alignment=Right

[panel1]
height=40
iconSize=24
plugins=fancymenu, quicklaunch, taskbar, statusnotifier, tray, mount, volume, worldclock, showdesktop

[quicklaunch]
apps\1\desktop=/home/agustin/.local/share/applications/firefox-tab.desktop
apps\2\desktop=/usr/share/applications/qps.desktop
apps\3\desktop=/home/agustin/.local/share/applications/xfce4-terminal-tab.desktop
apps\size=3
alignment=Left
type=quicklaunch

[taskbar]
alignment=Left

[tray]
alignment=Right

[volume]
alignment=Right

[worldclock]
alignment=Right
